#define U______ KC_NO

// control
#define CT_A LCTL_T(KC_A)
#define CT_B LCTL_T(KC_B)
#define CT_C LCTL_T(KC_C)
#define CT_D LCTL_T(KC_D)
#define CT_E LCTL_T(KC_E)
#define CT_F LCTL_T(KC_F)
#define CT_G LCTL_T(KC_G)
#define CT_H LCTL_T(KC_H)
#define CT_I LCTL_T(KC_I)
#define CT_J LCTL_T(KC_J)
#define CT_K LCTL_T(KC_K)
#define CT_L LCTL_T(KC_L)
#define CT_M LCTL_T(KC_M)
#define CT_N LCTL_T(KC_N)
#define CT_O LCTL_T(KC_O)
#define CT_P LCTL_T(KC_P)
#define CT_Q LCTL_T(KC_Q)
#define CT_R LCTL_T(KC_R)
#define CT_S LCTL_T(KC_S)
#define CT_T LCTL_T(KC_T)
#define CT_U LCTL_T(KC_U)
#define CT_V LCTL_T(KC_V)
#define CT_W LCTL_T(KC_W)
#define CT_X LCTL_T(KC_X)
#define CT_Y LCTL_T(KC_Y)
#define CT_Z LCTL_T(KC_Z)
#define CT_SCLN LCTL_T(KC_SCLN)
#define CT_ESC LCTL_T(KC_ESC)
#define CT_1 LCTL_T(KC_1)
#define CT_F1 LCTL_T(KC_F1)
#define CT_0 RCTL_T(KC_0)
#define CT_F10 RCTL_T(KC_F10)
#define CT_BTN3 LCTL_T(KC_BTN3)

// control + the key
#define Ct_A C(KC_A)
#define Ct_B C(KC_B)
#define Ct_C C(KC_C)
#define Ct_D C(KC_D)
#define Ct_E C(KC_E)
#define Ct_F C(KC_F)
#define Ct_G C(KC_G)
#define Ct_H C(KC_H)
#define Ct_I C(KC_I)
#define Ct_J C(KC_J)
#define Ct_K C(KC_K)
#define Ct_L C(KC_L)
#define Ct_M C(KC_M)
#define Ct_N C(KC_N)
#define Ct_O C(KC_O)
#define Ct_P C(KC_P)
#define Ct_Q C(KC_Q)
#define Ct_R C(KC_R)
#define Ct_S C(KC_S)
#define Ct_T C(KC_T)
#define Ct_U C(KC_U)
#define Ct_V C(KC_V)
#define Ct_W C(KC_W)
#define Ct_X C(KC_X)
#define Ct_Y C(KC_Y)
#define Ct_Z C(KC_Z)
#define Ct_PGUP C(KC_PGUP)
#define Ct_PGDN C(KC_PGDN)
#define Ct_HOME C(KC_HOME)
#define Ct_LEFT C(KC_LEFT)
#define Ct_RGHT C(KC_RGHT)
#define Ct_END C(KC_END)
#define Ct_GRV C(KC_GRV)
#define Ct_DEL C(KC_DEL)
#define Ct_BSPC C(KC_BSPC)
#define Ct_SLSH C(KC_SLSH)

// shift + key
#define St_TAB S(KC_TAB)

// alt
#define AT_A ALT_T(KC_A)
#define AT_B ALT_T(KC_B)
#define AT_C ALT_T(KC_C)
#define AT_D ALT_T(KC_D)
#define AT_E ALT_T(KC_E)
#define AT_F ALT_T(KC_F)
#define AT_G ALT_T(KC_G)
#define AT_H ALT_T(KC_H)
#define AT_I ALT_T(KC_I)
#define AT_J ALT_T(KC_J)
#define AT_K ALT_T(KC_K)
#define AT_L ALT_T(KC_L)
#define AT_M ALT_T(KC_M)
#define AT_N ALT_T(KC_N)
#define AT_O ALT_T(KC_O)
#define AT_P ALT_T(KC_P)
#define AT_Q ALT_T(KC_Q)
#define AT_R ALT_T(KC_R)
#define AT_S ALT_T(KC_S)
#define AT_T ALT_T(KC_T)
#define AT_U ALT_T(KC_U)
#define AT_V ALT_T(KC_V)
#define AT_W ALT_T(KC_W)
#define AT_X ALT_T(KC_X)
#define AT_Y ALT_T(KC_Y)
#define AT_Z ALT_T(KC_Z)
#define AT_1 ALT_T(KC_1)
#define AT_2 ALT_T(KC_2)
#define AT_3 ALT_T(KC_3)
#define AT_4 ALT_T(KC_4)
#define AT_5 ALT_T(KC_5)
#define AT_6 ALT_T(KC_6)
#define AT_7 ALT_T(KC_7)
#define AT_8 ALT_T(KC_8)
#define AT_9 ALT_T(KC_9)
#define AT_0 ALT_T(KC_0)
#define AT_F1 ALT_T(KC_F1)
#define AT_F2 ALT_T(KC_F2)
#define AT_F3 ALT_T(KC_F3)
#define AT_F4 ALT_T(KC_F4)
#define AT_F5 ALT_T(KC_F5)
#define AT_F6 ALT_T(KC_F6)
#define AT_F7 ALT_T(KC_F7)
#define AT_F8 ALT_T(KC_F8)
#define AT_F9 ALT_T(KC_F9)
#define AT_F0 ALT_T(KC_F0)
#define AT_ESC ALT_T(KC_ESC)
#define AT_TAB ALT_T(KC_TAB)
#define AT_BTN2 ALT_T(KC_BTN2)

// gui
#define GT_B GUI_T(KC_B)
#define GT_D GUI_T(KC_D)
#define GT_E GUI_T(KC_E)
#define GT_F GUI_T(KC_F)
#define GT_K GUI_T(KC_K)
#define GT_L GUI_T(KC_L)
#define GT_M GUI_T(KC_M)
#define GT_P GUI_T(KC_P)
#define GT_T GUI_T(KC_T)
#define GT_V GUI_T(KC_V)
#define GT_W GUI_T(KC_W)
#define GT_Y GUI_T(KC_Y)
#define GT_Z GUI_T(KC_Z)
#define GT_ENT GUI_T(KC_ENT)
#define GT_ESC GUI_T(KC_ESC)
#define GT_SLSH GUI_T(KC_SLSH)
#define GT_3 GUI_T(KC_3)
// #define GT_F3   GUI_T(KC_F3)
#define GT_8 GUI_T(KC_8)

// shift
#define ST_A SFT_T(KC_A)
#define ST_B SFT_T(KC_B)
#define ST_C SFT_T(KC_C)
#define ST_D SFT_T(KC_D)
#define ST_E SFT_T(KC_E)
#define ST_F SFT_T(KC_F)
#define ST_G SFT_T(KC_G)
#define ST_H SFT_T(KC_H)
#define ST_I SFT_T(KC_I)
#define ST_J SFT_T(KC_J)
#define ST_K SFT_T(KC_K)
#define ST_L SFT_T(KC_L)
#define ST_M SFT_T(KC_M)
#define ST_N SFT_T(KC_N)
#define ST_O SFT_T(KC_O)
#define ST_P SFT_T(KC_P)
#define ST_Q SFT_T(KC_Q)
#define ST_R SFT_T(KC_R)
#define ST_S SFT_T(KC_S)
#define ST_T SFT_T(KC_T)
#define ST_U SFT_T(KC_U)
#define ST_V SFT_T(KC_V)
#define ST_W SFT_T(KC_W)
#define ST_X SFT_T(KC_X)
#define ST_Y SFT_T(KC_Y)
#define ST_Z SFT_T(KC_Z)
#define ST_COMM SFT_T(KC_COMM)
#define ST_ENT SFT_T(KC_ENT)
#define ST_ESC SFT_T(KC_ESC)
#define ST_SPC SFT_T(KC_SPC)
#define ST_TAB SFT_T(KC_TAB)
#define ST_UNDS SFT_T(KC_UNDS)
#define ST_SLSH SFT_T(KC_SLSH)
#define ST_ASTR SFT_T(KC_ASTR)
#define ST_1 SFT_T(KC_1)
#define ST_2 SFT_T(KC_2)
#define ST_3 SFT_T(KC_3)
#define ST_4 SFT_T(KC_4)
#define ST_5 SFT_T(KC_5)
#define ST_6 SFT_T(KC_6)
#define ST_7 SFT_T(KC_7)
#define ST_8 SFT_T(KC_8)
#define ST_9 SFT_T(KC_9)
#define ST_0 SFT_T(KC_0)
#define ST_F1 SFT_T(KC_F1)
#define ST_F2 SFT_T(KC_F2)
#define ST_F3 SFT_T(KC_F3)
#define ST_F4 SFT_T(KC_F4)
#define ST_F5 SFT_T(KC_F5)
#define ST_F6 SFT_T(KC_F6)
#define ST_F7 SFT_T(KC_F7)
#define ST_F8 SFT_T(KC_F8)
#define ST_F9 SFT_T(KC_F9)
#define ST_F10 SFT_T(KC_F10)
#define ST_F11 SFT_T(KC_F11)
#define ST_F12 SFT_T(KC_F12)
#define ST_____ SFT_T(KC_NO)

// one shot mod
#define OSM_LST OSM(MOD_LSFT)
#define OSM_RST OSM(MOD_RSFT)

// ctrl alt, trans
#define CTAT___ MT(MOD_LCTL | MOD_LALT, _______)

// switch back to last application
// ctrl+tab
// switch ctrl+shift+tab
// app fwrd, app_back
// #define APP_FWD GUI_T(C(KC_TAB))
// #define APP_BCK ALT_T(C(S(KC_TAB)))
// not working, switch off for now
// #define APP_FWD KC_LGUI
// #define APP_BCK KC_LALT
