#define U______ KC_NO

// control
#define CT_A    LCTL_T(KC_A)
#define CT_B    LCTL_T(KC_B)
#define CT_C    LCTL_T(KC_C)
#define CT_D    LCTL_T(KC_D)
#define CT_E    LCTL_T(KC_E)
#define CT_F    LCTL_T(KC_F)
#define CT_G    LCTL_T(KC_G)
#define CT_H    LCTL_T(KC_H)
#define CT_I    LCTL_T(KC_I)
#define CT_J    LCTL_T(KC_J)
#define CT_K    LCTL_T(KC_K)
#define CT_L    LCTL_T(KC_L)
#define CT_M    LCTL_T(KC_M)
#define CT_N    LCTL_T(KC_N)
#define CT_O    LCTL_T(KC_O)
#define CT_P    LCTL_T(KC_P)
#define CT_Q    LCTL_T(KC_Q)
#define CT_R    LCTL_T(KC_R)
#define CT_S    LCTL_T(KC_S)
#define CT_T    LCTL_T(KC_T)
#define CT_U    LCTL_T(KC_U)
#define CT_V    LCTL_T(KC_V)
#define CT_W    LCTL_T(KC_W)
#define CT_X    LCTL_T(KC_X)
#define CT_Y    LCTL_T(KC_Y)
#define CT_Z    LCTL_T(KC_Z)
#define CT_SCLN RCTL_T(KC_SCLN)
#define CT_1    LCTL_T(KC_1)
#define CT_F1   LCTL_T(KC_F1)
#define CT_0    RCTL_T(KC_0)
#define CT_F10  RCTL_T(KC_F10)

#define Ct_A    C(KC_A)
#define Ct_B    C(KC_B)
#define Ct_C    C(KC_C)
#define Ct_D    C(KC_D)
#define Ct_E    C(KC_E)
#define Ct_F    C(KC_F)
#define Ct_G    C(KC_G)
#define Ct_H    C(KC_H)
#define Ct_I    C(KC_I)
#define Ct_J    C(KC_J)
#define Ct_K    C(KC_K)
#define Ct_L    C(KC_L)
#define Ct_M    C(KC_M)
#define Ct_N    C(KC_N)
#define Ct_O    C(KC_O)
#define Ct_P    C(KC_P)
#define Ct_Q    C(KC_Q)
#define Ct_R    C(KC_R)
#define Ct_S    C(KC_S)
#define Ct_T    C(KC_T)
#define Ct_U    C(KC_U)
#define Ct_V    C(KC_V)
#define Ct_W    C(KC_W)
#define Ct_X    C(KC_X)
#define Ct_Y    C(KC_Y)
#define Ct_Z    C(KC_Z)




// alt
#define AT_A    ALT_T(KC_A)
#define AT_I    ALT_T(KC_I)
#define AT_L    RALT_T(KC_L)
#define AT_S    LALT_T(KC_S)
#define AT_2    LALT_T(KC_2)
#define AT_F2   LALT_T(KC_F2)
#define AT_9    RALT_T(KC_9)
#define AT_F9   RALT_T(KC_F9)

// gui
#define GT_B    GUI_T(KC_B)
#define GT_D    GUI_T(KC_D)
#define GT_E    GUI_T(KC_E)
#define GT_K    GUI_T(KC_K)
#define GT_T    GUI_T(KC_T)
#define GT_Z    LGUI_T(KC_Z)
#define GT_SLSH RGUI_T(KC_SLSH)
#define GT_3    LGUI_T(KC_3)
// #define GT_F3   GUI_T(KC_F3)
#define GT_8    GUI_T(KC_8)

// shift
#define ST_A    SFT_T(KC_A)
#define ST_B    SFT_T(KC_B)
#define ST_C    SFT_T(KC_C)
#define ST_D    SFT_T(KC_D)
#define ST_E    SFT_T(KC_E)
#define ST_F    SFT_T(KC_F)
#define ST_G    SFT_T(KC_G)
#define ST_H    SFT_T(KC_H)
#define ST_I    SFT_T(KC_I)
#define ST_J    SFT_T(KC_J)
#define ST_K    SFT_T(KC_K)
#define ST_L    SFT_T(KC_L)
#define ST_M    SFT_T(KC_M)
#define ST_N    SFT_T(KC_N)
#define ST_O    SFT_T(KC_O)
#define ST_P    SFT_T(KC_P)
#define ST_Q    SFT_T(KC_Q)
#define ST_R    SFT_T(KC_R)
#define ST_S    SFT_T(KC_S)
#define ST_T    SFT_T(KC_T)
#define ST_U    SFT_T(KC_U)
#define ST_V    SFT_T(KC_V)
#define ST_W    SFT_T(KC_W)
#define ST_X    SFT_T(KC_X)
#define ST_Y    SFT_T(KC_Y)
#define ST_Z    SFT_T(KC_Z)
#define ST_COMM SFT_T(KC_COMM)
#define ST_ENT  SFT_T(KC_ENT)
#define ST_SPC  SFT_T(KC_SPC)
#define ST_UNDS SFT_T(KC_UNDS)
#define ST_5    LSFT_T(KC_5)
#define ST_F5   LSFT_T(KC_F5)

// one shot mod
#define OSM_LST OSM(MOD_LSFT)
#define OSM_RST OSM(MOD_RSFT)

// ctrl alt, trans
#define CTAT___ MT(MOD_LCTL|MOD_LALT, _______)
        